<div class="alert alert-info">

# PSY 4016-G-H20
# Cueillette et traitement des données en neurosciences cognitives
## Chapitre 2: les structures de données, intro
<p>
<li> Structures de données:
    <ul>
        <li>la chaîne
        <li>l'entier
        <li>la flotte
        <li>la liste
        <li>le tuple
        <li>le dictionnaire
        <li>Pandas DataFrame
        <li>Numpy</ul>

<li> Les styles d'écriture de code python
<li> Indexation des structures de données
<li> Le Pseudo-code

<div class="alert alert-info">
<h3>Les structures de données</h3>
</div>

<div class="alert alert-success">
<br>
<li>Les chaînes de caractères (texte) en python sont entourés de guillemets simples ou de guillemets doubles.
<li>les entiers sont des nombres
<li>les flottantes sont des nombres avec une valeur après la virgule
<li>la liste est une séquance de variables
<li>le tuple est une séquance de variables NON modifiable
<li>le dictionnaire est une structure avec de clés et de valeurs. Le dictionnaire N’EST pas une sequence
<p><p>
<li>les listes, tuples, dictionnaires, DataFrames sont hétérogènes et peuvent contenir:<ul>
    <li> des chaînes de caractères (strings)
    <li>des entiers
    <li>des objets</ul>
</div>

<div class="alert alert-success">

### comment créer une structure de données :

### chaîne:
    str()
    variable1 = str("variable")

### entiere:
    int()
    entiere1 = int(1)

### flottante:
    float()
    flottante1 = float(1)

### list - structure entre crochets:
    list()
    list1 = list()
    list1 =[]

### tuple - structure entre parenthèses:
    tuple()
    tuple1 = tuple()
    tuple1 = ()

### dictionnaire - structure entre accolades:
    dict()
    dictionnaire1 = dict()
    dictionnaire1 = {}

### pandas DataFrame:
    pandas.DataFrame()
    df1 = pandas.DataFrame()

</div>

<div class="alert alert-success">
    
## commandes python
    
#### pour vérifier le type de variable, utilisez la commande :
    
    type()
    
#### pour vérifier le type de variable, utilisez la commande :
    
    len()
</div>

In [1]:
# créer une chaîne

a = str("bonjour") #Version 1
#a = "bonjour" #Version 2

print(a)
type(a)

bonjour


str

In [19]:
len(a)

In [1]:
# Vous pouvez affecter une chaîne multiligne 
# à une variable en utilisant trois guillemets:

a = """Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."""
# print(a)

In [2]:
len(a)

123

In [2]:
# créer une entier

i = 300
print(i)
type(i)

300


int

In [4]:
# exception:

len(i)

TypeError: object of type 'int' has no len()

In [6]:
# solution de contournement
len(str(i))

3

In [7]:
# créer une flottante

flottante1 = float(1)
print(flottante1)
type(flottante1)

1.0


float

In [34]:
# exception:

len(flottante1)

In [36]:
# solution de contournement

len(str(flottante1))

In [55]:
# créer plusieurs variables:

text3, c, text4 = 'montreal', 4, '.ca'
print(text3, c, text4)

In [8]:
# créer une liste

ls1 = ['text1', 'b', 'text2', 'text', [], ()]
print(ls1)
type(ls1)

['text1', 'b', 'text2', 'text', [], ()]


list

In [ ]:
len(ls1)

In [11]:
# créer un tuple

tup1 = ('text1', 'b', 'text2', 'text')
print(tup1)
type(tup1)

tup2 = 'test1', 'text3'
print(tup2)
type(tup2)

In [ ]:
len(tup2)

<div class="alert alert-warning">

<li>les listes et le tuples sont des structures 1D
</div>

<center><img src="img/numpy_1x3x1.png"><center>

In [7]:
# créer un dictionnaire

d1 = {
    'cle1':'variable',
    'cle2':[],
    'cle3': [1,2,3],
    'cle4': ('a', 'b',)
    }
print(d1)
type(d1)

{'cle1': 'variable', 'cle2': [], 'cle3': [1, 2, 3], 'cle4': ('a', 'b')}


dict

In [18]:
len(d1)

4

In [21]:
# créer un pandas DataFrame
import pandas

df = pandas.DataFrame(d1)
print(df)
type(df)

ValueError: All arrays must be of the same length

In [20]:
len(df)

0

<div class="alert alert-warning">

les pandas DataFrames peuvent être créés à partir de:
<li> fichiers (csv, excel, json, etc.)
<li>listes
<li>dictionnaires
    </div>

In [11]:
# pandas dataframes du liste:

ls1 = ['text1', 'b', 'text2', 'text']
df_du_ls = pandas.DataFrame(ls1, index=)

print(df_du_ls)

       0
0  text1
1      b
2  text2
3   text


In [23]:
# pandas dataframes du dictionnaire:

data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
lstest = ['AA', 'BB', 'CC', 'DD']


df_d = pandas.DataFrame.from_dict(data, orient= 'index', columns= lstest ) # Version 1
print(df_d)

      AA BB CC DD
col_1  3  2  1  0
col_2  a  b  c  d


In [24]:
df_dv2 = pandas.DataFrame(data) # Version 2
print(df_dv2)

   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d


In [17]:
type(df_d)

pandas.core.frame.DataFrame

In [46]:
# par défault les collones de la cadre de données correspond aux clés
df_d

col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d

In [48]:
# pour changer la structure, le paramètre "orient" peut être utilisé

df_d = pandas.DataFrame.from_dict(data, orient = 'index')
df_d

0  1  2  3
col_1  3  2  1  0
col_2  a  b  c  d

In [54]:
# alternativement, la commande "transpose" peut être utilisée
# qui est similaire à Microsoft Excel et LibreOffice calc

df_d = pandas.DataFrame.from_dict(data)

print(df_d)
print(df_d.transpose())

col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d

In [55]:
df_d = pandas.DataFrame.from_dict(data)

print(df_d)
print(df_d.T)

0  1  2  3
col_1  3  2  1  0
col_2  a  b  c  d

In [21]:
# les noms des colonnes peuvent également
# être définis à l'intérieur de la commande d'exécution

df_d = pandas.DataFrame.from_dict(data, orient = 'index',
                                 columns = ['A','B','C','D'])
df_d
chemin = os.getcwd()
             
oa.listdir(chemin)

# pour plus d'info:
# https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html

NameError: name 'os' is not defined

<div class="alert alert-warning">

<li>le dictionnaire et pandas DataFrame sont des structures 2D: multiple listes/ tuples 1D
</div>

<center><img 
             

             src="img/numpy_5x5x1.png"><center>

<div class="alert alert-warning">

<li>les données 3D = multiple 2D sur plusieurs feuilles Excel
</div>

<center><img 
             src="img/numpy_5x5x3.png"><center>

<div class="alert alert-warning">

<li>données 4D =<ul>
    <li>1 dossier avec
    <li>multiple fichiers Excel (3D)
    <li>avec multiple feuilles (2D)</ul>
</div>

<div class="alert alert-warning">

<li>données 5D =<ul>
    <li>multiple dossiers avec
    <li>multiple fichiers Excel (3D)
    <li>avec multiple feuilles (2D)</ul>
</div>

<div class="alert alert-warning">
Comment créer une structure 3/4/5D en python?</div>

<div class="alert alert-success">
<h2>NumPy = Numerical Python</h2>
</div>

<div class="alert alert-success">
<b>pourquoi NumPy est-il nécessaire ?</b>
<ul> 
    <li> Les variables en python sont flexibles, mais le coût est une manipulation moins efficace des données.
    <li> numpy est de type fixe, ils manquent de flexibilité mais ils est beaucoup plus efficaces pour stocker et manipuler des données.</ul>

<li> Auteur original Travis Oliphant, première version 1995, dernière 6 janvier 2020
<li> Repository: ithub.com/numpy/numpy
<li> Ref: https://www.nature.com/articles/s41586-020-2649-2</div>

<div class="alert alert-success">
<ul> <b>Avantages contre MATLAB</b>
    <li> Matlab fonctionne avec un grand nombre de boîtes à outils supplémentaires qui doivent être achetées. En Python, numpy est intégré ainsi qu'avec des packages python gratuits complémentaires comme SciPy 
    <li> MATLAB est un logiciel propriétaire à source fermée. Un code dans MATLAB, ne peut être utilisé que par des personnes qui peuvent se permettre une licence pour l'exécuter. Python est un logiciel gratuit et open-source. Non seulement vous pouvez télécharger Python gratuitement, mais vous pouvez également télécharger, consulter et modifier le code source. Le code Python pourrait être partagé et exécuté par tout lecteur intéressé.
    <li> Le langage MATLAB est développé exclusivement par Mathworks. Si Mathworks devait cesser ses activités, MATLAB ne pourrait plus être développé et pourrait éventuellement cesser de fonctionner. Les parties sensibles aux performances de NumPy sont toutes écrites en langage C, donc elles sont <b>très rapides.</b></ul>
    <p>
<ul> <b>Limites</b>
    <li> insérer / ajouter n'est pas aussi simple que pour les listes
    <li> la concaténation ne lie pas les tableaux, mais en renvoie un nouveau
    <li> le remodelage n'est possible que si le nombre d'éléments ne change pas. Un pack de remplacement Blaze tente de surmonter ce problème
    <li> Les algorithmes qui ne sont pas exprimables en tant qu'opération vectorisée s'exécuteront généralement lentement, car ils sont implémentés en Python pur. Des compilations peuvent être utilisées pour éviter cela: scipy.weabe, numexpr, Numba, Cython</ul></div>

In [26]:
import numpy as np
np.__version__

'1.22.0'

<div class="alert alert-warning">
crée une structure numpy
<li><b>principe fondamental de NumPy = tableaux multi-dimensionnels</b>
    </div>

<div class="alert alert-warning">
<li>np.array
<li>np.empty
<li>np.zeros
<li>np.one
<li>np.full
<li>np.eye
<li>np.repeat
<li>np.linspace
<li>np.arange
<li>np.random
<li>np.random.random
<li>np.random.normal
<li>np.random.randint
</div>

In [27]:
# Créer des tableaux de données
# entier
arr0 = np.array([1, 2, 3])
arr0

array([1, 2, 3])

In [28]:
arr0.shape

(3,)

In [29]:
# flottante
np.array([1.1, 2.2, 3.3]) # version 1

array([1.1, 2.2, 3.3])

In [30]:
# Les valeurs peuvent être spécifiées avec dtype:

np.array([1,2,3,4,5], dtype='float32')  # version 2

array([1., 2., 3., 4., 5.], dtype=float32)

In [31]:
# multidimensionnel

arr1 = np.array([[1, 2], [3, 4]])
arr1

array([[1, 2],
       [3, 4]])

In [32]:
arr1.shape

(2, 2)

In [33]:
arr2 = np.array([[5, 6], [7, 8],[3, 5]])
arr2

array([[5, 6],
       [7, 8],
       [3, 5]])

In [ ]:
# créer des tableaux vides:
# numpy.empty(shape, dtype, order)

# shape (allure) = dimensions du tableaux
# dtype = le typage attendu lors de son rendu (optionnel)
# order (ordre) = pour un tableaux style C (C) ou FORTRAN (F)

np.empty([3,3], dtype=int)

In [ ]:
np.zeros(10, dtype=int)

In [ ]:
# Les valeurs peuvent être spécifiées avec dtype chaîne:

np.zeros(10, dtype='int16')

In [ ]:
# ou avec dtype objet:

np.zeros(10, dtype=np.int16)

In [ ]:
unes_tab = np.ones([2,2], dtype=float)
print(unes_tab)

In [ ]:
# faire un tableau 3x5 avec 3,14

np.full((3,5), 3.14)

In [34]:
# créer une matrice d'identité
# avec de 1 par diagonale:

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
# répéter

np.repeat(1,10)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [35]:
# faire un tableau de 5 valeurs régulièrement espacées:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [41]:
# trancher

# x[début : arrêt : étape]
# x[start : stop : step]

x = np.arange(10,15)
x

array([10, 11, 12, 13, 14])

In [37]:
# valeurs réparties équitablement
# numpy.arange(start, stop ,step, dtype)

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

In [ ]:
np.arange(1,10,3)

In [ ]:
np.arange(1,10,2,float)

In [28]:
# random
# valeurs aléatoires uniformément réparties:

x2 = np.random.random((3,3))
x2

In [ ]:
# aléatoire normalement distribué avec moyenne 0 et std 1:
np.random.normal(0,1, (3,3))

In [ ]:
# random entiers:
np.random.randint(0,10,(3,3))

<div class="alert alert-success">
<h2>Transformation Inter-Structure</h2>
</div>

In [27]:
# list -> dictionnaire:

ls1 = ['text1', 'b', 'text2', 'text', [], ()]

d1 = {"cle": ls1}
d1

{'cle': ['text1', 'b', 'text2', 'text', [], ()]}

In [28]:
# list -> pandas DataFrame:

df = pandas.DataFrame(ls1)
df

0
0  text1
1      b
2  text2
3   text
4     []
5     ()

In [30]:
# list -> numpy:

ordre = np.asarray(ls1)
ordre

# faites attention aux annonces concernant les changements
# dans les modules python.

C:\Users\Dylan\AppData\Local\Temp/ipykernel_205628/1848270402.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ordre = np.asarray(ls1)


array(['text1', 'b', 'text2', 'text', list([]), ()], dtype=object)

In [68]:
ordre = numpy.asarray(ls1, dtype = None)
ordre

In [33]:
# dictionnaire -> list:

d1 = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}

ls2 = d1["col_1"]
ls2

[3, 2, 1, 0]

In [34]:
ls3 = d1.keys()
ls3

dict_keys(['col_1', 'col_2'])

In [14]:
type(ls3)

dict_keys

In [16]:
# ATTENTION

ls4 = d1.keys().tolist()
ls4

# tolist() - ne fonctionne pour les keys / values d'un dictionnare

In [20]:
ls5 = list(d1.keys())
ls5

In [22]:
ls6 = list(d1.values())
ls6

In [35]:
# dictionnaire -> pandas DataFrame:

df2 = pandas.DataFrame(d1)
df3 = pandas.DataFrame.from_dict(d1)
print(df2)
print(df3)

   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d
   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d


In [37]:
# dictionnaire -> numpy:

list(d1.items())

np.asarray(list(d1.items()), dtype = dict)

array([['col_1', list([3, 2, 1, 0])],
       ['col_2', list(['a', 'b', 'c', 'd'])]], dtype=object)

In [38]:
# pandas DataFrame -> list:

df3.values.tolist()

[[3, 'a'], [2, 'b'], [1, 'c'], [0, 'd']]

In [39]:
df3.columns.tolist()

['col_1', 'col_2']

In [40]:
df3.col_1.tolist()

[3, 2, 1, 0]

In [54]:
# pandas DataFrame -> dictionnaire:

df3.to_dict()

In [56]:
# pandas DataFrame -> numpy:

ordre = numpy.array(df3)
ordre

In [32]:
# numpy -> list:

ordre = numpy.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

ls3 = ordre.tolist()
ls3

In [40]:
# numpy -> dictionnaire:

d3 = {"cle":ordre.tolist()}
# d3

In [30]:
# numpy -> pandas DataFrame:

df2 = pandas.DataFrame(ordre,
                   columns=['a', 'b', 'c'])
df2

<div class="alert alert-info">
<h3>Les styles d'écriture de code python </h3>
    "Code is more often read than written" - Guido van Rossum
</div>

In [ ]:
def ff(jj):
    oo = list(); jj = list(jj)
    for ii in jj: oo.append(str(ord(ii)))
    return '+'.join(oo)

In [ ]:
#ff('J\'aime python.')

<div class="alert alert-success">
<ul><b>Les noms</b>
    <li>Utilisez des noms descriptifs de plus d'un caractère (modules, variables)
    <li>Pour les variables et modules: utilisez les lettres minuscule et séparateur par soulignement
    </ul></div>

In [ ]:
# Écriture moche

a = 12
b = 24

In [ ]:
# Écriture agréable

n_filters = 12
n_freqs = 24

In [ ]:
# Écriture moche

import os as OperatingSystem

In [ ]:
# Écriture agréable

import numpy as np

<div class="alert alert-success">
<ul><b>Espacement</b>
    <li>un (et un seul) espace entre chaque élément
    <li>L’indexation et l’affectation n’ont pas d’espace entre ouverture et fermeture '()' ou '[]‘
    </ul></div>

In [1]:
# Écriture moche

my_var=1+2==3
my_list = [1,2,3,4]
el = my_list [1]

In [2]:
# Écriture agréable

my_var = 1 + 2 == 3
my_list = [1, 2, 3, 4]
el = my_list[1]

<div class="alert alert-success">
<ul><b>Importation des modules</b>
    <li>Importer un module par ligne
    <li>Eviter les importations ‘*’
    <li>Uitlisez l’ordre d’importation:<ol>
        <li>bibliothèque standard
        <li>autres paquets
        <li>code local / personnalisé</ol>
    </ul></div>

In [ ]:
# Écriture moche

from numpy import *

import os, sys

In [ ]:
# Écriture agréable

import os
import sys

import numpy as np

from my_personal_lib import my_variable

<div class="alert alert-success">
<ul>
    <li>Évité les déclarations condensées.
    <li>Privilégié les multilignes
    <li>PEP8 recommande que chaque ligne ait jusqu’à 79 charactères
    </ul></div>

In [ ]:
ma_liste_long = [1, 2, 3, 4, 5,
                6, 7, 8, 9, 10]

In [ ]:
# Écriture agréable

ma_liste_long = list(range(1,11))
ma_liste_long

<div class="alert alert-success">
<h4>Pour plus d'info:</h4>
<ul>
    <li>https://realpython.com/python-pep8/
    </ul></div>

<div class="alert alert-info">
<h3>Indexation des structures de données</h3>
</div>

<div class="alert alert-success">

dans python position 1 = 0
    
    0 1 2 3 4

l'indexation est une commande utilisée entre chochets et prend la position de la valeur
</div>

In [51]:
a = "bonjour"

print(a)

print(a[1])

bonjour
o


<div class="alert alert-success">

<li> l'indexation peut partir du début ou de la fin de la variable
<li> pour effectuer l'indexation à partir de la fin, utilisez le signe moins
</div>

In [42]:
a[-3]

'o'

<div class="alert alert-success">
<li> l'indexation peut extraire une partie de la variable
</div>

In [75]:
a[3:5]

In [74]:
a[3:]

In [45]:
a[:5]

'bonjo'

In [46]:
# l'indexation peut être utilisée pour inverser une variable

a[::-1]

'ruojnob'

<div class="alert alert-success">
<li> pour trouver la position de la valeur à l'intérieur de la variable, utilisez la commande : "index"
</div>

In [54]:
a.index('e')


6

<div class="alert alert-warning">

indexation des listes et tuples
    </div>

In [62]:
ls1 = ['text1', 'b', 'text2', 'text', [], ()]
ls1[4]

In [64]:
tup1 = ('text1', 'b', 'text2', 'text')
tup1[3]

In [77]:
ls1.index('text2')

In [ ]:
ls1[2:]

In [ ]:
ls1[:4]

In [ ]:
ls1[::-1]

In [67]:
# à resoudre

ls1[6]

In [10]:
ls_fruits = ['pomme','banane','orange','poire','raisins']

index = ls_fruits.index('banane')
print(ls_fruits[index])

<div class="alert alert-warning">

<li>Le dictionnaire N’EST pas une sequence
<li>l'indexation ne peut pas être utilisée sur les dictionnaires
    </div>

In [19]:
# pour accéder à toutes les clés :

# créer un dictionnaire

data = {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}

data.keys()

In [8]:
# pour afficher toutes les valeurs :

data.values()

In [21]:
# pour accéder à une valeur, utilisez la clé :

data['col_1']

<div class="alert alert-warning">

<li>l'indexation dans la base de données pandas est similaire à la liste et aux dictionnaires.
<li>la trame de données a une liste d'indices (l'index) et une liste de colonnes.
<li>l'index est un tableau immuable
<li>l'index peut être un ensemble / multiset ordonné, car les objets Index peuvent contenir des valeurs répétées
<li>les columns sont un objet Index contenant les étiquettes de colonne.
</div>

In [55]:
df1 = pandas.DataFrame(data)
print(df1)

   col_1 col_2
0      3     a
1      2     b
2      1     c
3      0     d


In [56]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [31]:
df1.columns

Index(['col_1', 'col_2'], dtype='object')

In [32]:
# la commande keys est dimilaire pour pandas
# est pour les dictionnaires

df1.keys()

Index(['col_1', 'col_2'], dtype='object')

In [36]:
# base de données Québec:
#    https://www.donneesquebec.ca/ -> 
#             Éducation et recherche -> 
#                  Projets d’infrastructure de recherche approuvés par le gouvernement du Québec
import pandas 
df_qc = pandas.read_csv (r"C:\Users\Dylan\Downloads\proj_infra_rechr_approu_20210423.csv")

df_qc = pandas.read_csv(r"C:\Users\Dylan\Downloads\proj_infra_rechr_approu_20210423.csv")
#df_qc = pandas.read_csv("C:/Users/Dylan/Desktop/UdeM_H22/PSY4016_traitementDeDonnees/ch_cours/proj_infra_rechr_approu_20210423.csv")
# # pour Windows:
# df_qc = pandas.read_csv(r'data\projinfrarechrapprou20200527.csv')

ParserError: Error tokenizing data. C error: Expected 1 fields in line 7, saw 2


In [35]:
df_qc

REGION_ADMINISTRATIVE                                 ETABLISSEMENT  \
0       Capitale-Nationale                              Université Laval   
1                   Estrie                      Université de Sherbrooke   
2                   Estrie                      Université de Sherbrooke   
3                 Montréal                             Université McGill   
4                 Montréal               École Polytechnique de Montréal   
...                    ...                                           ...   
1255    Capitale-Nationale                              Université Laval   
1256              Mauricie  Université du Québec à Trois-Rivières (UQTR)   
1257              Montréal                             Université McGill   
1258              Montréal                             Université McGill   
1259              Montréal                             Université McGill   

                               ETABLISSEMENT_PARTENAIRE ANNEE_FINANCIERE  \
0                                                   NaN        2010-2011   
1                                                   NaN        2010-2011   
2                                                   NaN        2010-2011   
3                                                   NaN        2010-2011   
4                                                   NaN        2010-2011   
...                                                 ...              ...   
1255                                                NaN        2019-2020   
1256                                                NaN        2018-2019   
1257  Centre universitaire de santé McGill (CUSM) - ...        2019-2020   
1258                                                NaN        2019-2020   
1259                                                NaN        2019-2020   

                            PROGRAMME  \
0     Fonds des leaders John-R.-Evans   
1     Fonds des leaders John-R.-Evans   
2     Fonds des leaders John-R.-Evans   
3     Fonds des leaders John-R.-Evans   
4     Fonds des leaders John-R.-Evans   
...                               ...   
1255  Fonds des leaders John-R.-Evans   
1256  Fonds des leaders John-R.-Evans   
1257  Fonds des leaders John-R.-Evans   
1258  Fonds des leaders John-R.-Evans   
1259  Fonds des leaders John-R.-Evans   

                                             VOLET RESPONSABLE_DU_PROJET  \
0                   Indépendant - chercheur établi   Clément M. GOSSELIN   
1     Indépendant - chercheur senior - recrutement       Michel HUNEAULT   
2     Indépendant - chercheur senior - recrutement       Stéphane MOREAU   
3                   Indépendant - chercheur établi         Jake BARRALET   
4     Indépendant - chercheur junior - recrutement           Guchuan ZHU   
...                                            ...                   ...   
1255  Indépendant - chercheur junior - recrutement   Céline VANEECKHAUTE   
1256                Indépendant - chercheur établi            Adam Duong   
1257  Indépendant - chercheur junior - recrutement           John Kildea   
1258                Indépendant - chercheur établi       Pedro ROSA-NETO   
1259                Indépendant - chercheur établi       Viviane YARGEAU   

                                                  TITRE     RESEAU  \
0     Laboratoire de recherche en coopération physiq...       MEES   
1         Caractérisation rhéologique des bioplastiques       MEES   
2     Infrastructure pour l'analyse tomographique no...       MEES   
3     Outil pour l'innovation en matière de matériau...  MEES,MSSS   
4     Laboratoire pour le contrôle avancé des micros...       MEES   
...                                                 ...        ...   
1255  Laboratoire sur l'ingénierie des procédés vert...       MEES   
1256  Matériaux innovants pour la conversion et le s...       MEES   
1257  Élaboration de stratégies pour mieux comprendr...       MSSS   
1258  Biomarqueurs sanguins des maladies du cerveau ...  MEES,MSSS   
125

In [47]:
df_qc.columns

In [43]:
df_qc.columns[0]

In [42]:
df_qc.columns[:5]

In [41]:
len(df_qc.columns)

In [46]:
df_qc.index

In [47]:
df_qc.index[1]

In [51]:
# découpage par index entier implicite:

df_qc[1:4]

In [35]:
df_qc.values

In [44]:
df_qc.values[0]

In [ ]:
df_qc['ETABLISSEMENT'][:5]

In [ ]:
df_qc['ETABLISSEMENT'][5:]

In [ ]:
df_qc['ETABLISSEMENT'][5:][:5]

In [ ]:
# affiche les 5 premières lignes

df_qc.head()

In [38]:
# affiche les 7 premières lignes

df_qc.head(7)

In [33]:
# affiche les 5 dernières lignes

df_qc.tail()

In [ ]:
df_qc.COUT_TOTAL.head()

In [ ]:
df_qc.COUT_TOTAL[:5]

In [ ]:
df_qc.COUT_TOTAL[-5:] # les valeurs de la fin

<div class="alert alert-warning">

indexation des tableaux numpy
    </div>

In [17]:
# Indexation des tableaux 1D

x

In [22]:
print(x[0],x[-1])

In [ ]:
# cinq premiers éléments

print(x[:5]

In [ ]:
# éléments après l'index 5

print(x[5:])

In [ ]:
# éléments entre index 4 et 7

print(x[4:7]

In [ ]:
# chaque élément à l'étape 2

print(x[::2]

In [ ]:
# chaque élément à l'étape 2, en commençant par l'index 1

print(x[1::2]

In [ ]:
# tous les éléments inversés

print(x[::-1]

In [ ]:
# inversé, à partir de l'index 5

print(x[5::-1]

In [33]:
# Indexation des tableaux 2D

x2

In [31]:
x2[2,0]

In [ ]:
# 2 lignes, 3 colonnes

print(x2[:2, :3]
print(x2[::-1, ::-1], '?')

In [ ]:
# print(x2[:3, ::2], 'toutes les lignes, toutes les deux colonnes')

In [ ]:
# Indexation des tableaux 3D

x3

In [ ]:
print(x3[:3, ::2])

<div class="alert alert-warning">

<h4>indexation numpy par list ou tableau</h4>
    </div>

In [ ]:
x1

In [ ]:
# une liste d'indices peut être fournie 

ind = [0,4,5]
x1[ind]

In [ ]:
# les valeurs peuvent être extraites à l'aide d'indices
# et envoyées immédiatement à une autre structure de type tableau-numpy

ind = np.array([[2,3],[4,5]])
x1[ind]

In [ ]:
x2

In [ ]:
# pour les tables multidimensionnelles,
# l'index de table doit être fourni 

x2[2,[2,0,1]]

In [38]:
# Recherhe de l'index

x.index(8)

# la commande "index" - ne peux pas s'appliqué

In [35]:
np.where(x == 8)

(array([8]),)

<div class="alert alert-success">
<h2>Attributes NumPy / Pandas</h2>
</div>

In [ ]:
# shape, size, dtype, itemsize, nbytes

# pour determiner
# la taille
# la forme
# la consummation de mémoire
# les types de données

# définir trois tableaux aléatoires (entiers normaux):
x1 = np.random.randint(10, size=6) #tableau 1D
x2 = np.random.randint(10, size=(3,4)) # tableau 2D
x3 = np.random.randint(10, size=(3,4,5)) # tableau 3D

In [ ]:
x3

In [ ]:
print(x3.ndim, x3.shape, x3.size, x3.dtype)

In [53]:
# méthodes supplémentaires pour analyser la structure.

print(df_qc.index.size)
print(df_qc.index.shape)
print(df_qc.index.ndim)
print(df_qc.index.dtype)

<div class="alert alert-info">
<h3>Pseudo-code</h3>
</div>

<div class="alert alert-success">
<b>Pseudo-code au format langage humain</b>
<li>avant de commencer à écrire de gros projets, il est conseillé de démarrer le projet avec un pseudo-code. 
<li>le pseudo-code décrit les étapes requises pour atteindre un objectif
<li>le pseudo-code peut être considéré comme une esquisse de haut niveau ou une description d'un programme.
<li>cela ressemblera typiquement à la structure d'un programme.
<li>le pseudocode peut être écrit dans un langage de niveau humain qui esquisse les tâches et le flux de contrôle général.
</div>

```
PseudoCode, langage niveau humain

Objective: envoyer une liste de courriels et
           créer un journal de ce qui a été envoyé.
Fonction1:
        * prend la liste des courriels
        * définir la sortie du fichier de journalisation
        * envoyer des courriels
        * ajouter des informations de journalisation sur les courriels
```

<div class="alert alert-success">
<b>Pseudo-code au format Python</b>
<br>
<li>peut être écrit beaucoup plus près de Python, y compris la syntaxe Python 
<li>il s’agit plutôt d’un modèle / schéma
<li>n'est parfois qu'un travail en cours qui n'est pas encore terminé
<li>Le mot clé "pass" - pass est un mot clé réservé, qui ne fait rien.
</div>

In [1]:
# PseudoCode pour une fonction permettant d'envoyer des courriels à une liste  
# d'adresses électroniques et de renvoyer un journal de ce qui a été envoyé

def envoyer_courriels(liste_adresses):

    courriels_envoyes = {}  # Définir une variable de sortie pour la journalisation

    for courriel in liste_adresses:

        # Envoyer l'email actuel
        pass

        # Ajouter les informations de journalisation de l'envoi de cet email
        courriels_envoyes[courriel] = True

    return courriels_envoyes

<div class="alert alert-danger">
<b>les commandes et codes à apprendre par cœur </b></div>

<div class="alert alert-danger">
<h3>Exercises</h3>
</div>

<div class="alert alert-success">
<ul> <b>veuillez écrire les réponses à ces questions:</b>
<li> Qu'est-ce qu'un entier ?
<li> Qu'est-ce qu'une chaîne ?
<li> Quelle est la différence entre un entier et un flottant?
<li> Qu'est-ce qu'une liste ?
<li> Quels sont les avantages d'un tuple ?

<li> Comment transformer une colonne pandas en liste ?
<li> Comment extraire la valeur de la liste située en position 10 ?

<li> Quelles sont les méthodes pour définir les variables ?
<li> Comment vérifier le type d'une variable ?
<li> Comment ajouter une variable à un tuple ?
<li> Comment envoyer toutes les valeurs d'une trame de données à une liste ?
<li> Comment créer une trame de données à partir d'une liste ?
<li> Comment accéder à une lettre dans une chaîne à une certaine position ?
<li> Comment définir plusieurs variables en même temps ?
<li> Définir un flottant
<li> Initialisez deux entiers : a = 0 et b = 10 
<li> Veuillez définir la liste : liste =[17, 38, 10, 25, 72]
<li> Triez et affichez la liste
<li> Ajoutez l’élément 12 à la liste et affichez la liste 
<li> Inversez et affichez la liste
<li> Affichez l’indice de l’élément 17
<li> Enlevez l’élément 38 et affichez la liste
<li> Affichez la sous-liste du 2e au 3e élément
<li> Affichez la sous-liste du début au 2e élément
<li> Affichez la sous-liste du 3e élément à la fin de la liste 
<li> Affichez la sous-liste complète de la liste
<li> Affichez le dernier élément en utilisant un indiçage négatif
<li>Créez un tableau numpy 1D de int de 0 à 9
<li>convertir un tableau 1D en tableau 2D avec 2 lignes
    </ul>
</div>

<div class="alert alert-success">
<li> Créer une liste
<li> ajouter une chaîne, un entier et un flottant à la liste
<li> ajouter la liste à 'key5' dans le dictionnaire
<li> temps pour résoudre - 2 minutes </div>

<div class="alert alert-success">
<li> créer une trame de données à l'aide du dictionnaire:
<li> d1 = {'Subj_ID': '001', 'score': 16, 'group' : 2, 'condition': 'cognition'}
<li> résoudre l'erreur en utilisant l'Internet
<li> temps pour résoudre - 2 minutes
</div>

<div class="alert alert-success">
<li> la commande ls_fruits[::2] qu'est ce que ça fait ?
</div>

In [5]:
ls_fruits = ['pomme','banane','orange','poire','raisins']
ls_fruits[::3]

['pomme', 'poire']

In [ ]:
# Créez un cadre de données de pandas
# à partir de chacun des éléments ci-dessous:

list('abcedfghijklmnopqrstuvwxyz')

np.arange(26)

In [39]:
##définir un dict
d = ({'cle1' : [2.3, 5, 4,4 ], 'cle2' : 'salut'})
d['cle1'] = [2,5,4,4]
print(d['cle1'])
d.keys()
d.items()




[2, 5, 4, 4]


dict_items([('cle1', [2, 5, 4, 4]), ('cle2', 'salut')])

In [45]:
tuple = (1,2,3)
print(tuple)
#dict1.values()
d.pop('cle1')
print(d)

    #del d[cle]

(1, 2, 3)


KeyError: 'cle1'

In [46]:
print(d)
d['cle2']

{'cle2': 'salut'}


'salut'