<div class="alert alert-info">

# PSY 4016-G-H20
# Cueillette et traitement des données en neurosciences cognitives
## Chapitre 3: Modification de données
<p>
<li> Modification des données
<li> Combinaison des données
<li> Les opérateurs
    <ul> <li>opérateurs de comparaison
    <li>opérateurs d'aggregation
    <li>opérateurs arithmétiques (incluses dans NumPy)
    <li>opérateurs trigonométrique; exponents, logarithms
    <li>opérateurs sur les valuers manquantes</ul>
<li> Pandas groupby

<div class="alert alert-info">
<h3>Modifications de données</h3></div>

<div class="alert alert-warning">
<h3>modification des valeurs des chaînes</h3>
</div>

In [3]:
a = "bonjour"
a

'bonjour'

In [4]:
 a[3] = "T"

# la chaîne est un objet immuable

TypeError: 'str' object does not support item assignment

In [5]:
a.index("j")

3

In [6]:
# remplacement des données dans la chaîne

a.replace("njo","nTo")

'bonTour'

In [7]:
# chaîne -> liste

a.split("n")

['bo', 'jour']

<div class="alert alert-warning">
<h3>modification des valeurs d'une liste</h3>
</div>

In [8]:
ls1 = [3, 2, 1, 0]

In [9]:
# ajout de données

ls1.append('text-ver2')
ls1

[3, 2, 1, 0, 'text-ver2']

In [10]:
# changement de données

ls1[1] = 7
print(ls1)

[3, 7, 1, 0, 'text-ver2']


In [16]:
# faire des copies

ls2 = ls1.copy()

In [17]:
ls1.remove(3)

ValueError: list.remove(x): x not in list

In [28]:
# ls1

In [19]:
ls1 = [3, 2, 1, 0]

ls1.pop(2)
ls1

[3, 2, 0]

In [20]:
ls1 = [3, 2, 1, 0]

ls1.sort()
ls1

[0, 1, 2, 3]

In [21]:
ls1.reverse()
ls1

[3, 2, 1, 0]

<div class="alert alert-warning">
<h3>modification des valeurs d'un tuple</h3>
</div>

In [22]:
tup1 = (3, 2, 1, 0)
tup1[1] = 7

TypeError: 'tuple' object does not support item assignment

In [18]:
# faire des copies

tup2 = tup1
print(tup2)

In [31]:
tup1.remove(3)

# Les tuples ne peuvent être changés, une fois définis
# Les tuples sont habituellement plus rapides que les listes

<div class="alert alert-warning">
<h3>modification des valeurs d'un dictionnaire</h3>
</div>

In [23]:
# ajout des valeurs
d1 = {
    'cle1':'variable',
    'cle2':[],
    'cle3': [1,2,3],
    'cle4': ('a', 'b',)
    }

d1['autre'] = 'valeur2'
d1

{'cle1': 'variable',
 'cle2': [],
 'cle3': [1, 2, 3],
 'cle4': ('a', 'b'),
 'autre': 'valeur2'}

In [24]:
# changements des valeurs:

d1['cle1'] = 'var 2'
d1['cle1']

'var 2'

In [25]:
# donnee la valeur de la clé SI elle existe

var = d1.get('cle3')
var

[1, 2, 3]

In [26]:
# supprimer une clé du dictionnaire SI elle existe

d1.pop('cle4')
d1

{'cle1': 'var 2', 'cle2': [], 'cle3': [1, 2, 3], 'autre': 'valeur2'}

In [30]:
d1 = {
    'cle1':'variable',
    'cle2':[],
    'cle3': [1,2,3],
    'cle4': ('a', 'b',)
    }

del d1['cle4']
d1

{'cle1': 'variable', 'cle2': [], 'cle3': [1, 2, 3]}

In [28]:
# # supprimer tous les élements du dictionnaire

d1.clear()
d1

{}

In [31]:
print(len(d1), len(d1['cle1']))

3 8


In [ ]:
# faire des copies

d3 = d1

In [22]:
d1

{'key': 'variable', 'key2': [], 'key3': [1, 2, 3], 'key4': ('a', 'b')}

In [23]:
d3

{'key': 'variable', 'key2': [], 'key3': [1, 2, 3], 'key4': ('a', 'b')}

In [24]:
d3['kqyky'] = 4.0
d3

{'key': 'variable',
 'key2': [],
 'key3': [1, 2, 3],
 'key4': ('a', 'b'),
 'kqyky': 4.0}

In [25]:
d1

{'key': 'variable', 'key2': [], 'key3': [1, 2, 3], 'key4': ('a', 'b')}

In [16]:
# créer une copie superficielle

d3 = d1.copy()

In [ ]:
# créer une copie complète

d3 = d1.deepcopy()

In [ ]:
import copy
d3 = copy.deepcopy(d1)

# Il faut créer une copie indépendante
# Sinon, les modifications apportées au dictionnaire copié
# vont également être envoyées à la version d'origine

In [ ]:
# plus d'info sur la différence entre copy et deepcopy

https://thispointer.com/python-how-to-copy-a-dictionary-shallow-copy-vs-deep-copy/
https://stackabuse.com/deep-vs-shallow-copies-in-python/#:~:text=Deep%20copy%20stores%20copies%20of%20an%20object's%20values,,implementation,%20I'd%20like%20you%20to%20imagine%20this%20scenario.
http://tech.quebecblogue.com/python-tips-copie-superficielle-copie-profonde-dans-python3/
https://www.ipgirl.com/675/quelle-est-la-difference-entre-une-copie-profonde-et-une-copie-superficielle.html    

<div class="alert alert-warning">
<h3>modification des valeurs d'un pandas DataFrame</h3>
    <li>loc (location)
    <li>iloc (index location)
    <li>at
</div>

In [77]:
import pandas

In [78]:
fichier = ""
df_qc.ETABLISSEMENT[1]

NameError: name 'df_qc' is not defined

In [21]:
# pour montrer la colonne

df_qc['ETABLISSEMENT']

In [ ]:
# semblable à la précédente; loc = location
    
df_qc.loc[:, 'ETABLISSEMENT']

In [ ]:
df_qc.iloc[1:]              # affiche toutes les lignes de 1 :; iloc = index-location

In [ ]:
df_qc.iloc[0:, [1,2]]       # affiche les lignes de 0 à : et les colonnes 1 et 2


In [20]:
df_qc.at[0,'ETABLISSEMENT']   # permet l'accès aux cellules
#index 0 et col 'str'

In [107]:
col = df_qc.columns[1] #
df_qc[col][:3]

0    Université du Québec à Chicoutimi (UQAC)
1             École Polytechnique de Montréal
2                    Université de Sherbrooke
Name: ETABLISSEMENT, dtype: object

In [108]:
df_qc.ETABLISSEMENT

0       Université du Québec à Chicoutimi (UQAC)
1                École Polytechnique de Montréal
2                       Université de Sherbrooke
3                       Université de Sherbrooke
4                               Université Laval
                          ...                   
1310                      Université de Montréal
1311                      Université de Montréal
1312             École Polytechnique de Montréal
1313                      Université de Montréal
1314      Université du Québec à Rimouski (UQAR)
Name: ETABLISSEMENT, Length: 1315, dtype: object

In [ ]:
df_qc.loc[1, 'ETABLISSEMENT'] = 'POLY'

In [ ]:
df_qc.at[2, 'ETABLISSEMENT'] = 'Sherbrooke'

In [113]:
df_qc.iloc[4, 1] = 'ULaval'

In [114]:
df_qc.ETABLISSEMENT

0       Université du Québec à Chicoutimi (UQAC)
1                                           POLY
2                                     Sherbrooke
3                       Université de Sherbrooke
4                                         ULaval
                          ...                   
1310                      Université de Montréal
1311                      Université de Montréal
1312             École Polytechnique de Montréal
1313                      Université de Montréal
1314      Université du Québec à Rimouski (UQAR)
Name: ETABLISSEMENT, Length: 1315, dtype: object

In [115]:
df_qc2 = df_qc

In [116]:
df_qc.ETABLISSEMENT.head(3)

0    Université du Québec à Chicoutimi (UQAC)
1                                        POLY
2                                  Sherbrooke
Name: ETABLISSEMENT, dtype: object

In [117]:
df_qc2.ETABLISSEMENT.head(3)

0    Université du Québec à Chicoutimi (UQAC)
1                                        POLY
2                                  Sherbrooke
Name: ETABLISSEMENT, dtype: object

In [118]:
df_qc2.at[1, 'ETABLISSEMENT'] = 'poly_new'

In [119]:
df_qc2.at[1, 'ETABLISSEMENT']

'poly_new'

In [120]:
df_qc.at[1, 'ETABLISSEMENT']

'poly_new'

In [ ]:
# faire des copies

df_qc = pandas.read_csv(fichier)
df_qc2 = df_qc.copy(deep=True)
df_qc2.at[1, 'ETABLISSEMENT'] = 'poly_new'
df_qc2.ETABLISSEMENT[1]
df_qc.ETABLISSEMENT[1]

In [ ]:
import copy
df_qc2 = copy.deepcopy(df_qc)
df_qc2.at[1, 'ETABLISSEMENT'] = 'poly_new'

In [40]:
df_qc3 = pandas.read_csv(fichier, usecols = ['ETABLISSEMENT', 'COUT_TOTAL'])

In [42]:
df_qc3.columns

In [50]:
df_qc4 = df_qc[["ETABLISSEMENT", "ETABLISSEMENT_PARTENAIRE",
       'ANNEE_FINANCIERE', 'PROGRAMME', 'VOLET', 'RESPONSABLE_DU_PROJET',
       'TITRE', 'RESEAU', 'MONTANT_MEES', 'MONTANT_MSSS', 'MONTANT_MEI',
       'MONTANT_TOTAL_QUEBEC', 'COUT_TOTAL']]

In [52]:
df_qc4.columns

In [ ]:
# df.department.tolist() permet d'extraire le contenu d'une col en une liste

ls_df = df.department.tolist()
#ls_df

In [ ]:
ls_df = list(df.items())

In [ ]:
ls_df[1]

In [121]:
# création d'une nouvelle colonne appelée «autre»

df_qc2['autre'] = 'valeur2'
#df_qc2['autre'][:5]

In [141]:
df_qc

In [143]:
# modification d'index -- prend une col et la définit en tant qu"index

df_qc.set_index('ETABLISSEMENT')

In [145]:
df_qc

In [157]:
df_qc.set_index('ETABLISSEMENT', inplace = True)
## pour faire le changeent, on peut utiliser inplace ou simplement stocker le changement dans un nouveau jeu de donées

In [146]:
df_qc3 = df_qc.set_index('ETABLISSEMENT')

In [159]:
df_qc

In [23]:
df_qc.index[1]

In [161]:
df_qc.at[1, 'COUT_TOTAL']
#contenu dans la ligne avec le nb 1 et la col "cout total" 

In [24]:
df_qc.index

In [165]:
df_qc.at['École Polytechnique de Montréal', 'COUT_TOTAL']
#

In [145]:
df_qc.to_excel('chemin/tmp2.xls')
df_qc.to_csv('chemin/tmp2.csv')

<div class="alert alert-warning">
<h3>modification des valeurs d'un tableau Numpy</h3>
<li> np.reshape
<li> np.newaxis
<li> copy
<li> changer les éléments
</div>

In [64]:
import numpy as np

In [63]:
x1

0       1
1       1
2       1
3       1
4       1
       ..
1030    1
1031    1
1032    1
1033    1
1034    1
Name: number, Length: 1035, dtype: int64

In [71]:
x1_2D = x1.reshape(0,1)
x1_2D

AttributeError: 'Series' object has no attribute 'reshape'

In [53]:
x1_2D2 = np.reshape(x1, (3, -1)) #-1 décide automatiquement le nombre de cols
x1_2D2

ValueError: Length of values (3) does not match length of index (1035)

In [72]:
# np.newaxis pour convertir un tableau 1D
# en un vecteur de ligne ou colonne

x1[:,np.newaxis]

C:\Users\Dylan\AppData\Local\Temp/ipykernel_162560/3934635628.py:4: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  x1[:,np.newaxis]


array([[1],
       [1],
       [1],
       ...,
       [1],
       [1],
       [1]], dtype=int64)

In [73]:
# changer de plus grandes tables

mon_tab = np.array(((6, 12, 93, 2),
                    (5, 26, 78, 90),
                    (3, 12, 16, 22),
                    (5, 3, 1, 16)))
mon_tab

array([[ 6, 12, 93,  2],
       [ 5, 26, 78, 90],
       [ 3, 12, 16, 22],
       [ 5,  3,  1, 16]])

In [74]:
mon_tab.shape

(4, 4)

In [75]:
mon_tab_remodel = np.reshape(mon_tab, (8,2))

In [76]:
m3 = mon_tab[:, np.newaxis]
m3

array([[[ 6, 12, 93,  2]],

       [[ 5, 26, 78, 90]],

       [[ 3, 12, 16, 22]],

       [[ 5,  3,  1, 16]]])

In [ ]:
m3.shape

In [ ]:
mon_tab

In [ ]:
np.reshape(mon_tab, (8,3))

In [ ]:
np.reshape(mon_tab, (8,-1))

In [ ]:
x2

In [ ]:
x2_v1 = x2[1:,2:].copy()
x2_v1

In [ ]:
x2_v2 = x2[:2, :2].copy()
x2_v2

In [ ]:
x2[0,0] = 12
x2

In [ ]:
x2[0,1] = 3.141
x2 # ? ou est la nouvelle valeur ?

<div class="alert alert-warning">
<b>REMARQUE ! </b>
<ul> contrairement aux listes, les tableaux numpy ont un type fixe, i.e., float in int = int</div>

<div class="alert alert-warning">
<b>trier les tableaux numpy</b>
<li> np.sort
<li> np.argsort</div>

In [35]:
a = np.array([2,5,3,7,5,3])
a
#np.sort(a)

array([2, 5, 3, 7, 5, 3])

In [31]:
a.sort()
a

array([2, 3, 3, 5, 5, 7])

In [38]:
np.argsort(a) #affiche les indices des éléments triés


array([0, 2, 5, 1, 4, 3], dtype=int64)

<div class="alert alert-info">
<h3>Combinaison des données</h3></div>

<div class="alert alert-warning">
<h3>combiner les chaînes</h3>
</div>

In [86]:
var2 = 12
var2

12

In [87]:
var1+var2

100

In [89]:
text3, c, text4 = 'montreal', 4, '.ca'

In [ ]:
text3

In [ ]:
text3, c, text4

In [ ]:
print(c)

In [90]:
print(text3+c)

TypeError: can only concatenate str (not "int") to str

In [ ]:
print(text3+str(c))

In [ ]:
# string() commands:


# len()
# strip()      # Les espaces de début sont supprimés
# strip(char)  # retourne une copie de la chaîne dans laquelle tous les caractères ont été supprimés du DÉBUT et de la FIN de la chaîne
# rstrip(char) # retourne une copie de la chaîne dans laquelle tous les caractères ont été supprimés de la FIN de la chaîne
# replace(char)
# split(char, char)
# find(char)
# isdigit()

In [49]:
s = 'bonjour'
# len(s) 
#s.find(j)
s.rfind('jo')
#s.rstrip('ur')
#s.replace('b','c')

3

In [ ]:
# all string methods:
https://docs.python.org/2/library/string.html
https://docs.python.org/3/library/stdtypes.html
https://www.programiz.com/python-programming/methods/string

In [92]:
a = "aBDnnc"

a.islower()

False

In [16]:
# ATTENTION avec strip(), rstrip()
# si la commande comprend plusieurs caractères,
# les caractères du milieu seront traités comme une commande de recherche

# ex2 = "texts.xlsx"
# ex2.strip(".xlsx")
# ex2.rstrip(".xlsx")

# ex3 = "textn.fini"
# ex3.strip(".fini")
# ex3.rstrip(".fini")

# ex4 = "textt.fiti"
# ex4.strip(".fiti")
# ex4.rstrip(".fiti")

# strip()  supprime les caractères du début et de la fin
# rstrip() supprime le caractères de la fin.

'tex'

<div class="alert alert-warning">
<h3>combiner les entieres et les flottants</h3>
</div>

In [93]:
i = 30

In [95]:
ii = i+7
ii

37

In [96]:
f = 3.0
f

3.0

In [97]:
ff = f+8
ff

11.0

In [98]:
fff = ff+ii
fff

48.0

In [99]:
f/i

0.1

In [100]:
ff/f

3.6666666666666665

In [ ]:
fi = float(i)
fi

In [101]:
iff = int(f)
iff

3

In [102]:
type(i)

int

In [ ]:
type(f)

In [104]:
text3
type(text3)

str

In [ ]:
# integer methods:

https://docs.python.org/3/library/stdtypes.html

In [ ]:
a = 7676

a.bit_length()

In [105]:
m = 8.0
m.is_integer()

True

<div class="alert alert-warning">
<h3>combiner les listes</h3>
</div>

In [47]:
# concatenation:

ls3 = ls1+ls1[2:]
ls3

['text1', 'b', 'text2', [], (), 'text-ver2', 'text2', [], (), 'text-ver2']

In [48]:
tup3 = tup1+tup1[-2:]
tup3

('text1', 'b', 'text2', 'text', 'text2', 'text')

In [ ]:
tup4 = ls1+tup1
tup4

In [ ]:
# commandes python utilisables sur les listes 
help(ls1)
len(ls)    # taille de la liste ls
sorted(ls) # enregistrera une liste triée

# commande spécifique pour les listes:
ls.sort    # affichera une liste triée mais ne l'enregistrera pas 
ls.append  # ajout d’un element à la fin de la liste ls
ls.reverse # inverser la liste ls
ls.index   # rechercher un élément dans la liste ls
ls.remove  # retirer un element de la liste ls
ls.pop     # retirer le dernier element de la liste ls

In [ ]:
ls1_sorted = sorted(ls1[:-3])
ls1_sorted

In [ ]:
a = [5, 2, 3, 1, 4]
a.sort()
a

In [59]:
ls_fruits = ["pomme",'banane','orange','poire','raisins']
fruits = pandas.DataFrame(ls_fruits)

In [60]:
fruits

0
0    pomme
1   banane
2   orange
3    poire
4  raisins

In [73]:
fruits.values

array([['pomme'],
       ['banane'],
       ['orange'],
       ['poire'],
       ['raisins']], dtype=object)

In [ ]:
fruits.to_csv("C:/Users/USER/Desktop/tmp.csv")

In [ ]:
# fruits.to_excel("C:/Users/USER/Desktop/tmp.csv")

<center><img src="img/Tableau_comparaison_liste_tuple.png"></center>

<div class="alert alert-warning">
<h3>combiner les dictionnaires</h3>
</div>

In [ ]:
# La concaténation des dictionnaires peut comporter des erreurs
# Vérifiez la version de python.

In [1]:
x = {'a': 1, 'b': 2}
y = {'b': 3, 'c': 4}

In [2]:
# python >3.9

z = x | y
z

# ATTENTION!
# la valeur des clés avec le même nom
# prendra TOUJOURS la valeur du deuxième dictionnaire

{'a': 1, 'b': 3, 'c': 4}

In [4]:
# python >3.5

z = {**x, **y}
z

{'a': 1, 'b': 3, 'c': 4}

In [11]:
# la fusion peut être effectuée en incluant de nouvelles clés:

z = {**x, 'foo': 1, 'bar': 2, **y}
z

In [13]:
# python 2

z = x.copy()
z.update(y) 
z

In [ ]:
# pour une réponse plus complète:
# https://stackoverflow.com/questions/38987/how-do-i-merge-two-dictionaries-in-a-single-expression-take-union-of-dictionari

<div class="alert alert-warning">
<h3>combiner les pandas.DataFrame</h3>
</div>

<div class="alert alert-success">
<ul> <h5>Concat/ Append</h5>
<li> Concat donne la flexibilité de rejoindre les jeux de données en fonction de l'axe (toutes les lignes ou toutes les colonnes)
<p><p> pandas.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=None, copy=True)<p>
<li> Append est le cas spécifique (axe = 0, join = 'outer') de concat. il a été écrit avant l'écriture de la fonction concat. il peut être supprimé dans les versions ultérieures.
<p><p> pandas.DataFrame.append(other, ignore_index=False, verify_integrity=False, sort=None)</ul>
<p>
<ul> <h5>Merge/ Join</h5>
<li> Merge est basée sur une colonne particulière de chacun des deux cadres de données, ces colonnes sont des variables comme «left_on», «right_on», «on»
<p><p> pandas.DataFrame.merge(right, how='inner', on=None, left_on=None, right_on=None, left_index=False, right_index=False, sort=False, suffixes=('_x', '_y'), copy=True, indicator=False, validate=None)<p>
<li> Join est basée sur les index et sur la façon dont les variable se combinent =['left','right','inner','outer']. Utilisez le join pour la jointure index sur index (par défaut) et colonne (s) sur index. Si vous vous joignez uniquement à l'index, vous souhaiterez peut-être utiliser join pour vous éviter de taper.
<p><p> pandas.DataFrame.join(self, other, on=None, how='left', lsuffix='', rsuffix='', sort=False)</ul></div>

<div class="alert alert-success">
<li> Créons deux cadres de données à partir de deux dictionnaires
</div>

In [32]:
df_A = pandas.DataFrame({'a':5, 'b':2, 'c':1}, index = [0])
df_B = pandas.DataFrame({'a':3, 'b':4, 'c':2}, index = [0])
df_C = pandas.DataFrame({'a':7, 'b':2, 'c':8}, index = [0])

In [35]:
df_A.append(df_B)

a  b  c
0  5  2  1
0  3  4  2

In [243]:
df_Concat = pandas.concat([df_A, df_B], axis = 0) # , axis=0 is default - pour les colonnes
df_Concat

a  b  c
0  1  2  2
0  3  4  2

In [244]:
df_Concat = pandas.concat([df_A, df_B], axis = 1) # axis=1 = pour l'index
df_Concat

a  b  c  a  b  c
0  1  2  2  3  4  2

In [245]:
pandas.concat([df_A, df_B], keys=['rouge','bleue'], axis=0)

a  b  c
rouge 0  1  2  2
bleue 0  3  4  2

In [50]:
df_office1 = pandas.DataFrame({'name':['Alana','Pierre','Corinne','Marianne'],
                           'group':['Bank','Science','Resources','Plannification']})
df_office2 = pandas.DataFrame({'name':['Alana','Pierre','Corinne','Marianne'],
                           'date':['2004','2008','2006','2012']})

In [54]:
pandas.concat([df_office1, df_office1])

name           group
0     Alana            Bank
1    Pierre         Science
2   Corinne       Resources
3  Marianne  Plannification
0     Alana            Bank
1    Pierre         Science
2   Corinne       Resources
3  Marianne  Plannification

In [55]:
pandas.concat([df_office1, df_office1])

group      name
0            Bank     Alana
1         Science    Pierre
2       Resources   Corinne
3  Plannification  Marianne
0            Bank     Alana
1         Science    Pierre
2       Resources   Corinne
3  Plannification  Marianne

In [56]:
pandas.concat([df_office1, df_office2], axis=1)

name           group      name  date
0     Alana            Bank     Alana  2004
1    Pierre         Science    Pierre  2008
2   Corinne       Resources   Corinne  2006
3  Marianne  Plannification  Marianne  2012

In [253]:
df_office1.merge(df_office2)

name           group  date
0     Alana            Bank  2004
1    Pierre         Science  2008
2   Corinne       Resources  2006
3  Marianne  Plannification  2012

In [257]:
df_office1

name           group
0     Alana            Bank
1    Pierre         Science
2   Corinne       Resources
3  Marianne  Plannification

In [258]:
df_office2

name  date
0     Alana  2004
1    Pierre  2008
2   Corinne  2006
3  Marianne  2012

In [256]:
df_office1.join(df_office2.set_index('name'), on='name')

name           group  date
0     Alana            Bank  2004
1    Pierre         Science  2008
2   Corinne       Resources  2006
3  Marianne  Plannification  2012

<div class="alert alert-warning">
<h3>combiner les numpy.array</h3>
</div>

<div class="alert alert-warning">
<ul> <b>Concatenation </b></div>

In [83]:
# concaténation de tableaux

tab1 = np.array(((1, 2),
                 (3, 4)))
tab2 = np.array(((5, 6),
                 (7, 8)))
tab3 = np.array(((9, 10),
                 (11, 12)))

In [84]:
tab1.shape

(2, 2)

In [86]:
tab1

array([[1, 2],
       [3, 4]])

In [93]:
concat1 = np.concatenate((tab1, tab2, tab3))

In [94]:
concat1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [95]:
concat1.shape

(6, 2)

In [97]:
# concaténation de tableaux, different types

a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print(a, b,c)

[1 2 3] [4 5 6] [7 8 9]


<center><img src="img/numpy_vstack_hstack.png"><center>

In [38]:
np.vstack([a,b,c]) #concaténation vertical

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
chk1 = np.vstack([a,b,c]) #concaténation vertical
print(chk1.shape, chk1.ndim)

(3, 3) 2


In [99]:
np.hstack([a,b,c]) #concaténation horizontale

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
chk_v = np.hstack([a,b,c]) #concaténation vertical
print(chk_v.shape, chk_v.ndim)

(9,) 1


In [101]:
np.c_[a,b,c] #concaténation vertical, Version 2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [102]:
np.r_[a,b,c] #concaténation horizontale, Version 2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<div class="alert alert-warning">
<b>Division de tableaux </b>
</div>

<div class="alert alert-success">
<li> np.split
<li> np.vsplit
<li> np.hsplit</div>

In [103]:
tab_concat = np.array(((1, 2),
                       (3, 4),
                       (5, 6),
                       (7, 8),
                       (9, 10),
                       (11, 12)))
tab_concat

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [105]:
tab_concat.shape, tab_concat.ndim

((6, 2), 2)

<center><img src="img/numpy_split.png"><center>

In [106]:
np.split(tab_concat, 3)

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

<center><img src="img/numpy_vsplit.png"><center>

In [107]:
# numpy.vsplit(ary, indices_or_sections)

np.vsplit(tab_concat, [3])

[array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])]

In [53]:
u1, u2 = np.vsplit(tab_concat, [3])
u1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [108]:
tab_concat

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [ ]:
[ 1,  2],[ 3,  4],

<center><img src="img/numpy_hsplit.png"><center>

In [81]:
u1, u2 = np.hsplit(tab_concat, [1])
u2

array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])

<div class="alert alert-info">
<h2>Les Operateurs</h2>
<ul> <li>opérateurs de comparaison
    <li>opérateurs d'aggregation
    <li>opérateurs arithmétiques (incluses dans NumPy)
    <li>opérateurs trigonométrique; exponents, logarithms
    <li>opérateurs sur les valuers manquantes</ul></div>

<div class="alert alert-warning">
<h3>opérateurs de comparaison</h3></div>

In [4]:
import pandas
fichier = r'C:\Users\Dylan\Downloads\proj_infra_rechr_approu_20210423.csv'
df_qc = pandas.read_csv(fichier)

df_qc = pandas.read_csv(fichier, usecols = ['REGION_ADMINISTRATIVE', 'ETABLISSEMENT'])

In [5]:
df_qc.columns

Index(['REGION_ADMINISTRATIVE', 'ETABLISSEMENT'], dtype='object')

In [6]:
# utiliser les méthodes de Bool pour examiner les 
# clés / indices et les valeurs - pour vérifier si la valeur est présente

'ETABLISSEMENT' in df_qc

True

In [11]:
'etab' in df_qc
df_qc.head
df_qc.col.tolist()

AttributeError: 'DataFrame' object has no attribute 'col'

In [7]:
df_qc[(df_qc["COUT_TOTAL"]>1400000) & (df_qc["COUT_TOTAL"]<5500000)]

KeyError: 'COUT_TOTAL'

In [ ]:
df_qc[df_qc.ETABLISSEMENT == 'Université de Montréal']

In [ ]:
df_qc[
    (df_qc.ETABLISSEMENT == 'Université de Montréal') &
    (df_qc.COUT_TOTAL < 100000)]

In [110]:
a = np.random.randint(10, size=8)

In [111]:
a

array([5, 2, 0, 5, 0, 7, 3, 8])

In [112]:
a<4

array([False,  True,  True, False,  True, False,  True, False])

In [89]:
a!=3

array([ True,  True,  True, False,  True,  True,  True,  True])

<div class="alert alert-warning">
<h3>opérateurs d'aggregation</h3></div>

In [23]:
import seaborn as sns
#pip3 install seaborn

In [24]:
# lecture à partir de jeux de données de modules:

planets = sns.load_dataset('planets')
#titanic = sns.load_dataset('titanic')
#iris = sns.load_dataset('iris')

planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [197]:
planets.head(10)

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009
5  Radial Velocity       1         185.840   4.80     76.39  2008
6  Radial Velocity       1        1773.400   4.64     18.15  2002
7  Radial Velocity       1         798.500    NaN     21.41  1996
8  Radial Velocity       1         993.300  10.30     73.10  2008
9  Radial Velocity       2         452.800   1.99     74.79  2010

In [198]:
planets.columns

Index(['method', 'number', 'orbital_period', 'mass', 'distance', 'year'], dtype='object')

In [211]:
# planets.head(3)

In [199]:
planets.count()

method            1035
number            1035
orbital_period     992
mass               513
distance           808
year              1035
dtype: int64

In [11]:
planets.max()

method            Transit Timing Variations
number                                    7
orbital_period                     730000.0
mass                                   25.0
distance                             8500.0
year                                   2014
dtype: object

In [10]:
planets.method.count(), len(planets.method)

(1035, 1035)

In [13]:
planets.mass.max()
planets.orbital_period.mad()


3181.7476426519697

In [209]:
ls = planets.method.tolist()
#ls

In [17]:
planets.method.value_counts()

Radial Velocity                  553
Transit                          397
Imaging                           38
Microlensing                      23
Eclipse Timing Variations          9
Pulsar Timing                      5
Transit Timing Variations          4
Orbital Brightness Modulation      3
Astrometry                         2
Pulsation Timing Variations        1
Name: method, dtype: int64

In [229]:
# planets.dropna().describe()

In [20]:
planets['number'].mean()
planets.number.mean()

1.7855072463768116

In [29]:
x1 = planets.number
np.any(x1 > 5)
planets.number.mean()

1.7855072463768116

In [77]:
np.sum(a>5)

2

In [16]:
import numpy as np 
np.sum(b ==3, axis=1) #nombre de valeurs = 3 dans chaque ligne

NameError: name 'b' is not defined

In [86]:
np.all(b<8) # toutes les valeurs sont-elles inférieures à 8?

False

<div class="alert alert-warning">
    <h3>opérateurs arithmétiques</h3></div>

<div class="alert alert-warning">
    <ul> <b>opérateurs arithmétiques - pandas</b></div>

In [184]:
df_qc['COUT/3'] = df_qc.COUT_TOTAL/3
#df_qc['COUT/3'].tail()
df_qc['COUT/3'].head(3)

ETABLISSEMENT
Université du Québec à Chicoutimi (UQAC)    4.859767e+05
École Polytechnique de Montréal             9.084913e+05
Université de Sherbrooke                    1.981616e+06
Name: COUT/3, dtype: float64

In [183]:
type(df_qc['COUT/3'][0])

numpy.float64

In [182]:
# df_qc.columns

In [185]:
df_qc['soustraction'] = df_qc['COUT_TOTAL'].subtract(df_qc['MONTANT_TOTAL_QUEBEC'])

In [186]:
df_qc['soustraction'].head()

ETABLISSEMENT
Université du Québec à Chicoutimi (UQAC)     874758
École Polytechnique de Montréal             1657488
Université de Sherbrooke                    3566908
Université de Sherbrooke                    2603516
Université Laval                            3317547
Name: soustraction, dtype: int64

<div class="alert alert-danger">
<h3>Exercise</h3>
<li> Comment vérifier si le code de soustraction est correct ?
</div>

In [189]:
df_qc.COUT_TOTAL.head()

ETABLISSEMENT
Université du Québec à Chicoutimi (UQAC)    1457930
École Polytechnique de Montréal             2725474
Université de Sherbrooke                    5944847
Université de Sherbrooke                    4248206
Université Laval                            5521200
Name: COUT_TOTAL, dtype: int64

In [190]:
df_qc.MONTANT_TOTAL_QUEBEC.head()

ETABLISSEMENT
Université du Québec à Chicoutimi (UQAC)     583172
École Polytechnique de Montréal             1067986
Université de Sherbrooke                    2377939
Université de Sherbrooke                    1644690
Université Laval                            2203653
Name: MONTANT_TOTAL_QUEBEC, dtype: int64

In [191]:
df_qc['soustraction'].head()

ETABLISSEMENT
Université du Québec à Chicoutimi (UQAC)     874758
École Polytechnique de Montréal             1657488
Université de Sherbrooke                    3566908
Université de Sherbrooke                    2603516
Université Laval                            3317547
Name: soustraction, dtype: int64

In [194]:
# vérification:
val1 = df_qc['COUT_TOTAL'][1]
val2 = df_qc['MONTANT_TOTAL_QUEBEC'][1]
finale = val1-val2

val3 = df_qc['soustraction'][1]
finale == val3

(df_qc.COUT_TOTAL[1])-(df_qc.MONTANT_TOTAL_QUEBEC[1]) == df_qc.soustraction[1]

True

In [192]:
df_test1 = df_qc.loc[df_qc.COUT_TOTAL>20000000, ['REGION_ADMINISTRATIVE', 'ANNEE_FINANCIERE']].head()
df_test1


REGION_ADMINISTRATIVE ANNEE_FINANCIERE
ETABLISSEMENT                                                
Université McGill                   Montréal        2009-2010
Université de Montréal              Montréal        2009-2010
Université McGill                   Montréal        2009-2010
Université Laval          Capitale-Nationale        2015-2016
Université McGill                   Montréal        2015-2016

In [12]:
df_test1.T

NameError: name 'df_test1' is not defined

In [177]:
# df_qc[df_qc.COUT_TOTAL > 200000]

In [179]:
# df_qc.loc[df_qc.COUT_TOTAL>20000000, ['REGION_ADMINISTRATIVE', 'ANNEE_FINANCIERE']].head()

In [ ]:
df_qc[(df_qc.COUT_TOTAL>1400000) & (df_qc.COUT_TOTAL<5500000)]

<div class="alert alert-warning">
    <ul> <b>opérateurs arithmétiques - NumPy</b></div>

In [ ]:
np.add			+	Addition (3 + 6 = 9)
np.subtract		-	Subtraction (6 – 3 = 3)
np.negative		-	Negation ( -3)
np.multiply		*	Multiplication (3 * 3 = 9)
np.divide		/	Division (6/3 = 2; 3/2 = 1)
np.floor_divide	//	Floor division (6//3 = 2; 3//2 = 1)
np.power		**	Exponentiation (3**3 = 27; 2**3 = 8)
np.mod			%	Modulus/remainder(9%3=0; 9%4 = 1)

In [15]:
# opérations arithmétiques 

arr1 = np.random.randint(5, size=4)
arr2 = np.random.randint(5, size=4)
arr1, arr2

(array([3, 3, 3, 1]), array([2, 3, 1, 0]))

In [114]:
# Ajouter des tableaux ensemble
arr1 + arr2

array([2, 2, 1, 4])

In [115]:
# Multiplication matricielle
arr1 * arr2

array([0, 0, 0, 4])

In [116]:
-arr1

array([-2,  0,  0, -2])

In [94]:
arr1**arr2

array([ 1, 27,  9,  4], dtype=int32)

In [16]:
import numpy as np
np.add(arr1, 2)

array([5, 5, 5, 3])

In [96]:
np.negative(arr1)

array([ 0, -3, -3, -4])

In [13]:
np.multiply(arr1, 3)

NameError: name 'np' is not defined

In [98]:
abs(arr1) #python command

array([0, 3, 3, 4])

In [99]:
np.absolute(arr1) #np command

array([0, 3, 3, 4])

In [19]:
np.add.reduce(arr1) # renvoie l'addition de tous les éléments


TypeError: add() takes from 2 to 3 positional arguments but 1 were given

In [124]:
np.multiply.reduce(a) #produire de multiplier tous les éléments

24

In [125]:
np.add.accumulate(a) #afficher toutes les valeurs intermédiaires

array([ 1,  3,  6, 10], dtype=int32)

In [126]:
np.multiply.outer(a,a) #créer une table de multiplication

array([[ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

<div class="alert alert-warning">
<h3>opérateurs trigonométrique; exponents, logarithms</h3></div>

In [117]:
exmpl = np.linspace(0, 4, 4)
exmpl

array([0.        , 1.33333333, 2.66666667, 4.        ])

In [ ]:
sin, cos, tan, arcsin, arccos, arctan

np.sin(exmpl)
np.cos(exmpl)
np.tan(exmpl)

exp, exp2, power, log, log2, log10

np.exp(exmpl)
np.exp2(exmpl)
np.log(exmpl)
np.log2(exmpl)
np.power(exmpl, 2)

In [102]:
np.power(exmpl, 2)

array([ 0.        ,  1.77777778,  7.11111111, 16.        ])

In [101]:
np.sin(exmpl)

array([ 0.        ,  0.9719379 ,  0.45727263, -0.7568025 ])

<div class="alert alert-warning">
<h3>opérateurs sur les valuers manquantes</h3></div>

<div class="alert alert-success">
<li>pandas marque les données manquantes avec NaN (pas un nombre) ou aucun (méthode du masque)
<li>NaN / None - ne sont pas disponibles pour tous les types de données
<li>-9999 (valeur sentinelle)
<li>la valeur sentinelle réduit la plage de valeurs valides pouvant être représentées et peut nécessiter une logique supplémentaire dans l'arithmétique CPU et GPU</div>

In [210]:
# quand quelque chose manque, pandas fusionne la cellule avec NaN:

A = {'a':1, 'b':2}
B = {'b':3, 'c':4}

df_na = pandas.DataFrame([A, B])

In [211]:
df_na

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [212]:
type(df_na['a'][0])

numpy.float64

<div class="alert alert-success">
<li>isnull()&nbsp;&nbsp;&nbsp;&nbsp; = générer un masque booléen indiquant les valeurs manquantes
<li>notnull()&nbsp; = opposé à isnull()
<li>dropna() = renvoie une version filtrée des données, les NaN sont supprimés
<li>fillna()&nbsp;&nbsp;&nbsp;&nbsp; = renvoie une copie des données avec les valeurs manquantes renseignées ou imputées</div>

In [213]:
# df_na.isnull()
df_na.isna()

a      b      c
0  False  False   True
1   True  False  False

In [214]:
df_na.notnull()
# df_na.notna()

a     b      c
0   True  True  False
1  False  True   True

In [215]:
df_na.dropna() # supprime les colonnes où au moins un élément est manquant

Empty DataFrame
Columns: [a, b, c]
Index: []

In [216]:
df_na['a'].isnull().values.any()
# df_na.a.isnull().values.any()

True

In [246]:
#df_na['a']

In [217]:
df_na['a'].fillna(0)

0    1.0
1    0.0
Name: a, dtype: float64

In [219]:
df_na['a'].fillna(3)

0    1.0
1    3.0
Name: a, dtype: float64

In [250]:
#df_na.fillna(0)

In [ ]:
# plus d'informations ici:

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html

<div class="alert alert-info">
<h3>Groupby: pandas.DataFrame.groupby</h3></div>

<div class="alert alert-success">
<li> DataFrame.groupby(by=None, axis=0, level=None, as_index=True, sort=True, group_keys=True, squeeze=False, observed=False, **kwargs)

<p>

groupby s'effectue en 3 étapes:

<li> <b>fractionnement</b> pour scinder et grouper un Cadre de données en fonction de la valeur de la clé spécifiée
<li> <b>application</b> pour calculer une fonction (agrégat, transformation, filtrage, au sein des groupes individuels)
<li> <b>combinaison</b> fusionne les résultats dans un tableau de sortie.

In [79]:
planets.columns

Index(['method', 'number', 'orbital_period', 'mass', 'distance', 'year'], dtype='object')

In [80]:
planets.method.tolist()

['Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Radial Velocity',
 'Imaging',
 'Imaging',
 'Imaging',
 'Eclipse Timing Variations',
 'Imaging',
 'Imaging',
 'Imaging',
 'Imaging',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Eclipse Timing Variations',
 'Radial Velocity',
 'Radial Velocity',
 'Imaging',
 'Radial Veloc

In [82]:
planets.to_excel(r"C:\Users\Dylan\Downloads\tmp3.xls")

C:\Users\Dylan\AppData\Local\Temp/ipykernel_162560/569095186.py:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  planets.to_excel(r"C:\Users\Dylan\Downloads\tmp3.xls")


ModuleNotFoundError: No module named 'xlwt'

In [20]:
planets.groupby('method').mean()

NameError: name 'planets' is not defined

In [265]:
planets.orbital_period[planets.method=='Astrometry'].mean()

631.1800000000001

In [266]:
planets.distance[planets.method=='Astrometry'].mean()

17.875

In [267]:
planets.groupby('method').groups.keys()

dict_keys(['Astrometry', 'Eclipse Timing Variations', 'Imaging', 'Microlensing', 'Orbital Brightness Modulation', 'Pulsar Timing', 'Pulsation Timing Variations', 'Radial Velocity', 'Transit', 'Transit Timing Variations'])

In [268]:
planets.groupby(['method','year']).first()

number  orbital_period  mass  distance
method                    year                                        
Astrometry                2010       1      1016.00000   NaN     14.98
                          2013       1       246.36000   NaN     20.77
Eclipse Timing Variations 2008       2      5767.00000   NaN    130.72
                          2009       1     10220.00000  6.05       NaN
                          2010       2      5573.55000   NaN    500.00
...                                ...             ...   ...       ...
Transit                   2014       1         3.57532   NaN    322.00
Transit Timing Variations 2011       2       160.00000   NaN   2119.00
                          2012       2        57.01100   NaN    855.00
                          2013       2        22.33950   NaN    339.00
                          2014       3             NaN   NaN       NaN

[69 rows x 4 columns]

In [ ]:
planets.groupby('method')['year'].describe()

In [269]:
#dispatch:

planets.groupby('method')['year'].describe().unstack()

       method                       
count  Astrometry                          2.0
       Eclipse Timing Variations           9.0
       Imaging                            38.0
       Microlensing                       23.0
       Orbital Brightness Modulation       3.0
                                         ...  
max    Pulsar Timing                    2011.0
       Pulsation Timing Variations      2007.0
       Radial Velocity                  2014.0
       Transit                          2014.0
       Transit Timing Variations        2014.0
Length: 80, dtype: float64

In [ ]:
# python commands:
# help(i)
sorted()

<div class="alert alert-danger">
<b>les commandes et codes à apprendre par cœur </b></div>

<div class="alert alert-danger">
<h3>Exercises</h3>
</div>

<div class="alert alert-success">
<li> Comment ajouter une variable à un tuple ?
<li> Triez et affichez la liste
<li> Ajoutez l’élément 12 à la liste et affichez la liste 
<li> Enlevez l’élément 38 et affichez la liste
<li>convertir un tableau 1D en tableau 2D avec 2 lignes
    </ul>
</div>

<div class="alert alert-success">
<li> Comment concaténer 2 listes ?
<li> Comment concaténer un tuple et une liste ?
<li> Quelles sont les commandes habituelles utilisées pour travailler avec une liste ?
<li> Quelles sont les commandes pour travailler avec une chaîne ?
</ul>
</div>

In [7]:
# Trouvez l'erreur
list1 = ['1','2','3', 4, '5', 6, 'c']
list2 = ['a','b','c','d']
list3 = ('e','f','g','h')

print(list1+list1['3'])
#print(list1[3]+list2)
#print(list1+list3)

TypeError: list indices must be integers or slices, not str

In [29]:
planets.head()
decade = 10 * (planets['year'] // 10)
decade


0       2000
1       2000
2       2010
3       2000
4       2000
        ... 
1030    2000
1031    2000
1032    2000
1033    2000
1034    2000
Name: year, Length: 1035, dtype: int64

<div class="alert alert-success">
<li> Décrivez les étapes du code 'CODE GROUPBY EXERCISE'
<li> Qu'est-ce que la fonction fillna() apportera au code final?
</div>

In [202]:
# CODE GROUPBY EXERCISE

decade = decade.astype(str) + 's'
decade.name = 'decade'
planets.groupby(['method' , decade])['number'].sum().unstack().fillna(0)

decade                         1980s  1990s  2000s  2010s
method                                                   
Astrometry                       0.0    0.0    0.0    2.0
Eclipse Timing Variations        0.0    0.0    5.0   10.0
Imaging                          0.0    0.0   29.0   21.0
Microlensing                     0.0    0.0   12.0   15.0
Orbital Brightness Modulation    0.0    0.0    0.0    5.0
Pulsar Timing                    0.0    9.0    1.0    1.0
Pulsation Timing Variations      0.0    0.0    1.0    0.0
Radial Velocity                  1.0   52.0  475.0  424.0
Transit                          0.0    0.0   64.0  712.0
Transit Timing Variations        0.0    0.0    0.0    9.0

In [18]:
# Créez un cadre de données de pandas
# à partir  des éléments ci-dessous:

mydict = dict(zip(mylist, myarr))

NameError: name 'mylist' is not defined

In [8]:
# Combinez ls1 et dict1 pour former une base de données

ls1 = list('abcedfghijklmnopqrstuvwxyz')
dict1 = {i: [str(i)+'_'+str(i*2)] for i in range(1,len(ls1))}

In [17]:
np.concatenate

{1: ['1_2'],
 2: ['2_4'],
 3: ['3_6'],
 4: ['4_8'],
 5: ['5_10'],
 6: ['6_12'],
 7: ['7_14'],
 8: ['8_16'],
 9: ['9_18'],
 10: ['10_20'],
 11: ['11_22'],
 12: ['12_24'],
 13: ['13_26'],
 14: ['14_28'],
 15: ['15_30'],
 16: ['16_32'],
 17: ['17_34'],
 18: ['18_36'],
 19: ['19_38'],
 20: ['20_40'],
 21: ['21_42'],
 22: ['22_44'],
 23: ['23_46'],
 24: ['24_48'],
 25: ['25_50']}

Créez un tableau numpy 3 × 3 de tous les True

In [15]:
import numpy as np
np.ones((2, 3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True]])

obtenir les positions de 2 élèments dans un tableau numpy, où les éléments A et B correspondent

joindre deux tableaux verticalement

In [ ]:
# réponses pour la quéstion dans chapitre 2

# version 1
d1 = {'Subj_ID':['001'],'score': [16], 'group': [2], 'condition': ['cognition']}
df_d = pandas.DataFrame(d1)

# version 2
d1 = {'Subj_ID':'001','score': 16, 'group': 2, 'condition': 'cognition'}
df_d = pandas.DataFrame(d1, index=[0])